Arbitrary unitaries
mainCSG/QuDiPy pull request #49
Opened 2021-07-27 18:59 UTC by zmerino

In response to issue #33, created a class called Unitary to take arbitrary unitary operators from the user in dictionary format. User can also specify a object file to load unitary operators from. There is a tutorial Unitary Operator Creation.ipynb which shows the basic functionality of the class.

2021-08-24 18:32 UTC, zmerino reviewed
I just made a commit which has some code changes. I also updated the QuDiPy tutorial data sharpoint directory: Added Unitary Operator.npz and created Uknown_slice folder under Pre-processed potentials.

2022-01-31 17:53 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                    raise ValueError("Operator entry contains a non-sqaure"+
```suggestion
                    raise ValueError("Operator entry contains a non-square"+
```

2022-01-31 17:56 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                    raise ValueError("Operator entry contains a non-sqaure"+
This is not a mistake, but apparently, single quotes are now considered the "good" style of Python in all cases.

2022-01-31 18:24 UTC, hromecB commented on qudipy/qutils/matrices.py
> +            Name of the file with extension .npz for the operator object.
perhaps, it's better to allow for both "Filename.npz" and "Filename" strings (so that the second one would be automatically completed to "Filename.npz")?

2022-01-31 18:39 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    # Ladder operatorss X_k ± i Y_k
```suggestion
    # Ladder operators X_k ± i Y_k
```

2022-01-31 18:41 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        u_k = PAULI_I
although redundant, I'd add an else clause here for readability (cf. if clause on line 212)

2022-01-31 18:42 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def sigma_plus(self,N, k):
```suggestion
    def sigma_plus(self, N, k):
```

2022-01-31 18:44 UTC, hromecB commented on qudipy/qutils/matrices.py
> +            + complex(0.0, 1.0) * self.construct(N,k,self.operators['PAULI_Y']))
all's good though impressively explicit 😂 I'd just write 1j instead of complex(0.0, 1.0)

2022-01-31 18:45 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def sigma_minus(self,N, k):
```suggestion
    def sigma_minus(self, N, k):
```

2022-01-31 18:48 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        Defines matrix that projects k-th qubit on the state |0〉
I used this elsewhere in the code but since the name is "e_up", the ket state should look like |↑〉.
To fix it only in one place, I suggest the following: 
```suggestion
        Defines matrix that projects k-th qubit on the state |↑〉≡ |0〉
```

2022-01-31 18:49 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        Defines matrix that projects k-th qubit on the state |1〉
same thing as above
```suggestion
        Defines matrix that projects k-th qubit on the state |↓〉≡ |1〉
```

2022-01-31 18:54 UTC, hromecB commented on qudipy/spinsimulator/spin_simulator.py
>  consts = Constants("vacuum")
okay for now but eventually the "constants" object should be either completely expelled from spin simulator, or incorporate the precise values from scipy.constants by default. I began to address this matter in the Control branch

2022-01-31 19:03 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def construct(self, N, k, O):
Based on the use of this function below, I think that its syntax can be simplified. In particular, I suggest that you change the 3rd argument to the string that is the key to a prototypical operator from `self.operators` dict: 
```
self.construct(N, k, self.operators['PAULI_Y'])) --> self.construct(N,  k, 'PAULI_Y')
```

This is clearly more concise but also equivalent. The motivation is that this is a regular (not static) method linked to the Unitary class instance. Thus, I think it should construct the operators using only the prototypes included in the `self.operators` dictionary; in this case, referencing only the string key (but not the operator itself) is sufficient

2022-01-31 20:10 UTC, hromecB commented on qudipy/qutils/matrices.py
> -PAULI_I = np.array([[1, 0], [0, 1]], dtype=complex)
I am convinced that these 4 Pauli operators should be standard elements of each self.operators dictionary, as you reference them everywhere else in the code, and they form a basis of 2x2 matrices - building blocks for other operators. Right now you explicitly indicate them when creating a Unitary class object (as in the tutorial), but I think that the end user should be released of this responsibility (otherwise the rest of the code will simply not work if a user doesn't do this!).

2022-02-01 17:22 UTC, zmerino commented on qudipy/qutils/matrices.py
> +            Name of the file with extension .npz for the operator object.
I think this is a good idea. Added.

2022-02-03 17:45 UTC, hromecB commented on qudipy/qutils/matrices.py
> +class Unitary:
As we discussed before, the name should be changed, since the projection and raising/lowering operators are not unitary. 
"Operator"? Other suggestions? 
The filename `matrices.py` should probably be changed accordingly.

2022-02-03 17:45 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    Initialize unitary class. Handles all things realted to
name change (see comment above)

2022-02-03 17:47 UTC, hromecB commented on qudipy/qutils/matrices.py
> +
Now, this is a default operator, so it should not be defined again.

2022-02-03 17:47 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        Defines a raising operators of the k-th qubit
```suggestion
        Defines a raising operator of the k-th qubit
```

2022-02-03 17:48 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        Defines a lowering operators of the k-th qubit
```suggestion
        Defines a lowering operator of the k-th qubit
```

2022-02-03 17:49 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                    raise ValueError('Operator {} is not unitary.'.format(key))
This requirement should be lifted (not all of them are unitary)

2022-02-03 17:54 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                self.operators = operators
If "Operator" is chosen to be the class name, maybe, we should rename this attribute somehow? As well as the keyword parameter of the `__init__` method?

2022-02-03 17:54 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                    raise ValueError('Operator entry contains a non-sqaure'+
```suggestion
                    raise ValueError('Operator entry contains a non-square'+
```

2022-02-03 17:59 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                        '{} is not complex.'.format(key))
In my opinion, a good style would be to fix the input under the hood whenever possible and throw an exception only if it can't be done. Therefore, I suggest that:
- > A square 2d list/tuple is converted to a NumPy array automatically
- > If the array can be cast to `complex` type, do that automatically

2022-02-03 18:01 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                I = np.eye(N,N,dtype=complex)
This will be redundant when you remove the unitarity requirement.

2022-02-03 18:19 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def construct(self, N, k, O):
I suggest adding a default flag to the definition of this method: `update_dict=False` (you can choose another name if you want). If `True`, the constructed operator will be added to the `self.operators` dictionary right away. The default syntax for the key name can be chosen, for example, as:
```
    your_method.__name__+'_{}_{}'.format(N, k)
```

2022-02-03 18:33 UTC, hromecB commented on qudipy/qutils/matrices.py
You can overload the bracket operators to simplify referencing the dictionary even more:
`self.operators['PAULI_I'] --> self['PAULI_I']`

To do that, add the following code but double-check it works as it should (adapted from https://stackoverflow.com/questions/1957780/how-to-override-the-operator-in-python):

```suggestion
    def __getitem__(self, key):
        return self.operators['key']    # you can also handle a KeyError here if you want
        
    def __setitem__(self, key, val):
        self.add_operators({key : val})
        
    def __delitem__(self, key):
        del self.operators['key']
```

After you ensure it works, please simplify the code of this type everywhere: `self.operators['PAULI_I'] --> self['PAULI_I']`

2022-02-03 18:40 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def load_ops(self, filename):
Please add a keyword boolean argument like `msg`, `message`, `output`, `print`, etc., (whatever name you prefer) to have the ability to suppress the printed message. You can choose `True` or `False` as the default value depending on what is more applicable. The point is not to have too many messages if you call the function multiple times.

2022-02-03 18:40 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def add_operators(self, new_ops):
Please add a keyword boolean argument like `msg`, `message`, `output`, `print`, etc., (whatever name you prefer) to have the ability to suppress the printed message. You can choose `True` or `False` as the default value depending on what is more applicable. The point is not to have too many messages if you call the function multiple times.

2022-02-03 18:40 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def remove_operators(self, op_names):
Please add a keyword boolean argument like `msg`, `message`, `output`, `print`, etc., (whatever name you prefer) to have the ability to suppress the printed message. You can choose `True` or `False` as the default value depending on what is more applicable. The point is not to have too many messages if you call the function multiple times.

2022-02-03 21:21 UTC, hromecB commented on qudipy/qutils/matrices.py
> +            Matrix for SWAP gate
```suggestion
            Matrix for sqrt(SWAP) gate 
```

2022-02-03 21:25 UTC, hromecB commented on qudipy/qutils/matrices.py
> +
In principle, we can also add a "power-SWAP" gate (i.e. SWAP to any power), since it's directly realizable in the pulse design algorithm I present in the thesis. The same applies to the qubit rotation operator around an arbitrary axis. 

Leave this for now (it's not a high priority), but we should probably add this in the future.

2022-02-03 21:35 UTC, hromecB commented on tutorials/Unitary Operator Creation.ipynb
> +    "If no Unitary Operators.npz file exist an object, called ops, can be initialized with an hard coded operator dictionary or left as an empty dictionary. For the tutarial examples that follow you
**General comment to the whole tutorial**: please split each code cell so that you have __no more than one__ print statement in each cell. Otherwise, it may be hard to identify which output corresponds to each line of code. 

Overall, Brandon set the bad tone for the style of tutorials, in my opinion. In particular, I believe that:
- > The in-built syntax for markdown cells is very powerful to make the explanations clear and catchy. Thus, there should be minimum `#comments` in the code but rather full-fledged markdown cells with bold, italic text, links, bullets, etc.
- > Individual `print` statements should be separated from each other (same as comment above)

2022-02-03 21:54 UTC, hromecB commented on tutorials/Unitary Operator Creation.ipynb
> +    "If no Unitary Operators.npz file exist an object, called ops, can be initialized with an hard coded operator dictionary or left as an empty dictionary. For the tutarial examples that follow you
okay, I'm confused now. Have you fixed this so fast, or it was good from the beginning but displayed badly on my laptop for some reason?

2022-02-03 21:56 UTC, hromecB commented on tutorials/Unitary Operator Creation.ipynb
> +    "\n",
For the learner, it will not be convenient to re-run the tutorial many times to go past all the errors that occur. Thus, please explicitly handle the exceptions everywhere

2022-02-03 21:57 UTC, hromecB commented on tutorials/Unitary Operator Creation.ipynb
> +   "source": [
See my comment above: this types of data can be converted directly to complex arrays and thus should not throw exceptions

2022-02-03 21:58 UTC, hromecB commented on tutorials/Unitary Operator Creation.ipynb
> +    "\n",
Should be removed, since not all operators we're dealing with here are unitary

2022-02-03 22:02 UTC, hromecB requested changes
One additional comment: do you think you can add 1-2 unit tests to this code? 
Other than that, I think I'm done with my review of this pull request. 
Double-check everything works (esp. all tutorials & unit tests) after you're finished with the requested changes, and notify me about it. 
The code will most likely be ready to merge at that time.

2022-02-05 20:38 UTC, zmerino commented on qudipy/qutils/matrices.py
> +                I = np.eye(N,N,dtype=complex)
What do think about restructuring the operator object as follows:
```
default_ops = { 
            'PAULI_X': 
                {
                    'op': np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex),
                    'info':
                        {
                        'unitary':True,
                        'eignenval': <list>,
                        'eigenvec': <list of list>,
                        .
                        .
                        .
                        <etc>
                        }
                }
            }
 ```
So that instead of calling an operator as `<object instance>.operators['<operator name>']` it would be called as `<object instance>.op_lib['<operator name>']['op']`

This would allow for operator meta data to be tracked

2022-02-07 20:28 UTC, hromecB commented on qudipy/qutils/matrices.py
> +                I = np.eye(N,N,dtype=complex)
To be honest with you, I think it overcomplicates the code structure. The shorter the function call, the better. 
Whether the operators are unitary or not is probably the only information that will be needed; I don't think we need to store the eigenvalues/ eigenvectors that we don't use anywhere (from what I remember). 
For this purpose, you can create (1) a binary attribute that will show whether or not all operators in the dictionary are unitary, _and/or_ (2) a function with no arguments that will output the same thing. If (1) (I prefer this option), then it can be updated every time a user adds new elements to the dictionary. In my opinion, only tracking all elements at once is practical. If the class object handles operators from a quantum circuit, then, obviously, all of them must be unitary. Conversely, when the only purpose of the class instance is to store a dictionary of different operators (applicable to the spin simulator, for instance), then it doesn't matter. 

Your suggestion gave me an idea, though, of how to rename everything. 
Class `Operator', as we already discussed. 
Dictionary attribute just called `lib`. This will reduce the call to `<object instance>.lib['<operator name>']`
Attribute/ function handling unitarity named `unitary`, `is_unitary`, etc.

2022-02-09 15:17 UTC, zmerino commented on tutorials/Unitary Operator Creation.ipynb
> +    "If no Unitary Operators.npz file exist an object, called ops, can be initialized with an hard coded operator dictionary or left as an empty dictionary. For the tutarial examples that follow you
I think I was editing it while you were commenting on it lol. I agree on the cleaning up the block comment explanations and formatting them into markdown cells.

2022-02-09 15:18 UTC, zmerino commented
I've added some unit tests.

2022-02-10 14:19 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        # Retrive method name of caller method
```suggestion
        # Retrieve method name of the caller method
```

2022-02-10 14:30 UTC, hromecB commented on qudipy/qutils/matrices.py
> +            if save is True:
this is a bad style for boolean variables:
just `if op_exist` and `if save`

2022-02-10 14:33 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    def sigma_plus(self, N, k, save=None, case='style 1'):
The default value of "save" should be boolean (in this case, `False`, I think), as you specify in the description of this function

2022-02-10 15:57 UTC, zmerino commented on qudipy/qutils/matrices.py
> +    def construct(self, N, k, O):
Functionality was added, as well as, a conditional save feature for hard coded operators. The save feature (most of code is defined in "man_coded_ops") was made to handle arbitrary user defined operators.

2022-02-10 16:25 UTC, zmerino commented on qudipy/qutils/matrices.py
> +    def sigma_plus(self, N, k, save=None, case='style 1'):
Yes, this should be false.

2022-02-10 17:23 UTC, zmerino commented on qudipy/qutils/matrices.py
> +
Added __repr__ because this creates a computer and human friendly way to read relevant information. In this case I just output the operator library file (if it exists) and the current operator key names for the instances of the object.

2022-02-10 18:13 UTC, hromecB commented on tutorials/Operator Creation.ipynb
> +    "If no Unitary Operators.npz file exist an object, called ops, can be initialized with an hard coded operator dictionary or left as an empty dictionary. For the tutarial examples that follow you
__Also__, there's something wrong with the beginning of this sentence
```suggestion
    "If no Unitary Operators.npz file exist an object, called ops, can be initialized with a hardcoded operator dictionary or left as an empty dictionary. For the tutorial examples that follow you will use Unitary Operators Tutorial.npz object file which you will create now."
```

2022-02-10 18:14 UTC, hromecB commented on tutorials/Operator Creation.ipynb
> +    "# Initialize unitary object:\n",
probably, a misplaced comment

2022-02-10 18:18 UTC, hromecB commented on tutorials/Operator Creation.ipynb
> +    "This tutorial will teach you how to interface with the unitary class in matrices.py to add/remove general unitary operators from the Unitary Operators.npz object file. The Unitary Operators.npz
You renamed the file. Also, please delete the old one
```suggestion
    "This tutorial will teach you how to interface with the unitary class in matrices.py to add/remove general unitary operators from the Operators Tutorial.npz object file. The Operators Tutorial.npz object contains a dictionary of unitary operators. The key expresses the name of the unitary while the value associated with the key is a complex-valued array. This tutorial will focus on creating and modifying a unitary object file named Unitary Operators Tutorial.npz. There exist a copy of the file under the QuDiPy tutorial data directory."
```

2022-02-10 18:30 UTC, hromecB commented on unit_tests/pytest.ini
> +    op_lib_monipulation:
there's no hidden meaning, just a typo, right? 
```suggestion
    op_lib_manipulation:
```

2022-02-10 18:39 UTC, hromecB commented on unit_tests/qutils_test/test_matrices.py
> +# Test that oparator library object's attribute is being tracked correctly
```suggestion
# Test that operator library object's attribute is being tracked correctly
```

2022-02-10 18:39 UTC, hromecB commented on unit_tests/qutils_test/test_matrices.py
> +    assert op.is_unitary == False
`assert not op.is_unitary`

2022-02-10 18:39 UTC, hromecB commented on unit_tests/qutils_test/test_matrices.py
> +    assert op.is_unitary == True
```suggestion
    assert op.is_unitary
```

2022-02-10 18:40 UTC, hromecB commented on unit_tests/qutils_test/test_matrices.py
> +import matplotlib.pyplot as plt
I think this is redundant

2022-02-10 18:45 UTC, hromecB commented on unit_tests/qutils_test/test_matrices.py
> +@pytest.mark.op_lib_monipulation
```suggestion
@pytest.mark.op_lib_manipulation
```

2022-02-11 15:36 UTC, hromecB commented on tutorials/Operator Creation.ipynb
> +    "ops1 = matr.Operator(operators=init_ops)\n",
Okay, I discovered a pretty serious problem. You don't test any of the hardcoded operators anywhere (neither here nor in the unit tests), thus the issues. 

First of all, for whatever reason, this ops1 object does not have a `self.filename` attribute.
I discovered it when trying to `print(ops1)` -- this gave me an error of `__repr__` function.
I'll point elsewhere in the code how to fix it.


Secondly, the `man_coded_ops` function clearly doesn't work as it should. When I try to create, e. g. `x = ops1.sigma_product(2,1,2)`, or `x = ops1.sigma_minus(2,1)`, I get a `None` in all cases. This is something I don't understand. 

When you fix it, please explicitly construct some high-dimensional operators in the tutorial and add at least 1 more unit test to make sure it works well.

2022-02-11 15:42 UTC, hromecB commented on qudipy/qutils/matrices.py
> +            self.filename = filename
This line means that the `self.filename` attribute is assigned only if there's an initial filename when creating an operator object. This manifests itself in issues with `__repr__()` function and some hardcoded operators that reference `save_ops(filename)` (these are the ones I spotted). 

To fix this, just move the code line to the left so that a filename (perhaps, 'None') is always saved
```suggestion
        self.filename = filename
```

2022-02-11 15:46 UTC, hromecB commented on qudipy/qutils/matrices.py
> +        # Define variable dictionary for key name styles
Zach, correct me if I don't understand something, but what I tried to convey is that keeping the general structure of `man_coded_ops` is fine, but for all hardcoded operators like `sigma_plus`, `cnot`, etc, there should not be a `case` keyword argument at all. The reason is simple: if a user chooses another style (say, '1 input' for SWAP), it will not work properly! It will either produce meaningless names like `SWAP_N2k1_1k2_None` or give errors (errors only so far in my tests).
Can you just move the definition of the `case` variable into the body of each function? This will solve the problem.
 
```suggestion
    def sigma_plus(self, N, k, save=False):
        '''
        Defines a raising operator of the k-th qubit
        Parameters
        ----------
        N : int
            Number of 1-qubit degrees of freedom in the operators.
        k : int
            Position of the raising operators in the tensor product.
        save : bool
            boolean indicator from original function call to save the operator
            to the library if true.
        case : string
            Is a string that specifies the naming style for the operator's key
            label. The default is of the form <operator name>_N#k#.
        Returns
        -------
        : complex 2D array
            The raising operators X_k + i Y_k
        '''
        #Define ??? (add best comment here)
        case='1 input'
        # Define variable dictionary for key name styles
```

2022-02-11 15:55 UTC, hromecB commented on qudipy/qutils/matrices.py
> +    ##### Hard Coded Operators #####
I just realized that the list of hard-coded operators lacks the __most common__ ones -- X, Y, Z in many dimensions. Meaning,  when PAULI_X is applied only on the kth qubit, whereas identity operators are applied on other ones.
It seems to me they were in this file in the past... called x(N, k), etc. Essentially, shortcuts for `self.construct(N,k,self.lib['PAULI_X']) ` etc.

Can you please add them here?

2022-02-12 22:40 UTC, zmerino commented on qudipy/qutils/matrices.py
> +            self.filename = filename
Thanks for catching this. This was a typo.

2022-02-12 22:45 UTC, zmerino commented on tutorials/Operator Creation.ipynb
> +    "ops1 = matr.Operator(operators=init_ops)\n",
Similar typo to the self.filename issue `return op` in man_coded_ops was indented one tab too many. This cause the operator to return `None` when an operator doesn't already exist in the operator library.

I have a test script that test the operator creation which I've been updating the unit test with (also the Jupyter notebook tutorial).

2022-02-12 22:58 UTC, zmerino commented on qudipy/qutils/matrices.py
> +        # Define variable dictionary for key name styles
I kept the case statement structure since this option required the least amount of copying and pasting of code into each hard coded operator. I do agree that the case statement structure is not robust to user errors, but I've gone and restructured the hard coded operators and the man_coded_ops function.

With regards to the hard coded operators, the general code structure is formatted as below. The main feature update is adding a struct function which will append the key value pairs to the method_name based on the users definition. The secondary update is storing the two nested function objects in the kwargs dictionary to be executed latter when called by coded_op (I updated the name).

```
# Structure for appened names formed from the kwarg keys and values
        def struct(key, val):
            # Ignored: struct and func 
            return f'_{key}{val}'

        # Define a function to construct the operator when needed
        def func(self):
            N_val = N
            k_val = k

            return self.construct(N_val,k_val,self.lib['PAULI_X'])

        # Define variable dictionary for operator
        kwargs = {'N': N, 'k': k, 'struct': struct, 'func': func}

        # Check if the operator exist or needs to be saved
        return self.coded_op(save, **kwargs)
```
In coded_op, I just added a for loop to append the desired key value pairs to the method name which called coded_op.

```

        # Define operator key name     
        curframe = inspect.currentframe()
        calframe = inspect.getouterframes(curframe, 2)
        method_name = calframe[1][3]

        # Append variable names and values to the operator name
        op_key = method_name
        for key, val in kwargs.items():
            if key not in ['struct', 'func']:
                op_key += kwargs['struct'](key, val)

        # If operator doesn's exist, save it if specified. If the operator does
        # exist then retrieve it from library
        if op_key in self.lib:
            # Retrieve operator
            return self.lib[op_key]
        else:
            # Compute operator for any specified function
            op = kwargs['func'](self)
            
            if save:
                # Construct dictionary item for operator
                operator_def = {
                        op_key: op
                }
                
                # Add operator to loaded dictionary
                self.add_operators(operator_def)
                # Save to operator library object
                self.save_ops(self.filename)

            return op
```

2022-02-13 20:45 UTC, merged